package replaydriver;

// generated by CLAP on Wed Jan 30 11:26:42 CST 2013
// Created for XXX JVM: 23.6-b04
import edu.hkust.clap.tracer.*;
import edu.hkust.clap.replayer.*;

public class ReplayDriver {

	public static void setUp(String[] args) throws Exception {
		TraceReader.setFileIndex(args);
		TraceReader.readTrace(1,"/home/gaoang/Java/Pecan/tmp/Clap2073321200085498286_monitordata.trace.gz");
		TraceReader.readTrace(2,"/home/gaoang/Java/Pecan/tmp/Clap2073321200085498286_threadNameToIdMap.trace.gz");
	}

	public static void main(String[] args) throws Throwable {

		setUp(args);

		new Thread("clap-main"){
			public void run(){
				// load arguments
				String[] mainargs = {};
				try {
					DataRace.main(mainargs);
				} catch (Throwable e) {
					e.printStackTrace();
				}
			}
		}.start();

		(new Scheduler()).start();

		//WAIT FOR 1 MINUTE TO STOP REPLAY
		//Thread.currentThread().sleep(60000);
	}
}

