#!/usr/bin/perl
#GoodBye World.
print "Goodbye Cruel World\n";
@lines = `perldoc -u -f atan2`;
foreach (@line){
    s/\w<([^>]+)>/\U$1/g;
    print;
}
$line = <STDIN>;
if ($lien eq "\n"){
    print "That was just a bland line !\n";
}else {
    print "That line of input was : $line ";
}
